{
  "data": {
    "id": "ember-data-3.12.6-ConflictError",
    "type": "class",
    "attributes": {
      "name": "ConflictError",
      "shortname": "ConflictError",
      "classitems": [],
      "plugins": [],
      "extensions": [],
      "plugin_for": [],
      "extension_for": [],
      "module": "@ember-data/adapter",
      "namespace": "",
      "file": "../adapter/addon/error.js",
      "line": 307,
      "description": "A `ConflictError` equates to a HTTP `409 Conflict` response status.\nIt is used by an adapter to indicate that the request could not be processed\nbecause of a conflict in the request. An example scenario would be when\ncreating a record with a client-generated ID but that ID is already known\nto the external API.",
      "extends": "AdapterError",
      "methods": [],
      "events": [],
      "properties": []
    },
    "relationships": {
      "parent-class": {
        "data": {
          "id": "ember-data-3.12.6-AdapterError",
          "type": "class"
        }
      },
      "descendants": {
        "data": []
      },
      "module": {
        "data": {
          "id": "ember-data-3.12.6-@ember-data/adapter",
          "type": "module"
        }
      },
      "project-version": {
        "data": {
          "id": "ember-data-3.12.6",
          "type": "project-version"
        }
      }
    }
  }
}